### PR TITLE
#Cleanup main.py, seperate into multiple files

### PR DESCRIPTION
**Pull request by Simon0x**
Take it if you want ^^
main.py get very big when we commit all things to one file....

### CODE REVIEW

**Comment by Simon0x** [comment]
fixed conflicts after merge of #21 to base.
think this is a usefull change. do this at start or later all forks will have big problems.

**Comment by MonsterMMORPG** [comment]
@DerScreever can you check whether the searching algorithm can be improved or not? i am running 3 instances and nothing worthy appears in my city :(

**Comment by DerScreever** [comment]
@monstermmorpg

What searching algorithm?

**Comment by tejado** [comment]
Sorry, rewrote the code more or less from scratch. But thanks a lot for your efforts.

**Pull request closed without merging**
