### PR TITLE
Minor fixes with trailing spaces and json file

### PR DESCRIPTION
**Pull request by frankhouzz**

### CODE REVIEW

**Comment by tejado** [comment]
Thanks for the PR. The additional spaces in the README are necessary for markdown syntax (e.g. double space at EOL is for a forced linebreak). Can you please revert it so I can accept your PR?

**Comment by frankhouzz** [comment]
Done :) Seems we are in different timezone.

**Comment by tejado** [comment]
Sorry, now it conflicts :x

**Comment by frankhouzz** [comment]
Solved.

**Pull request closed without merging**
