### PR TITLE
Add Google Auth

### PR DESCRIPTION
**Pull request by elliottcarlson**
Adds in Google Auth demo and provides a switch to login between the two

### CODE REVIEW

**Comment by dakk** [comment]
Yea, I see

**Comment by Simon0x** [comment]
Tested this solution.
For me it work.

**Comment by tejado** [comment]
Thanks a lot!

**Comment by 3mph4515** [comment]
@elliottcarlson Any chances to add 2FA via google? :)

**Comment by elliottcarlson** [comment]
I'll take a look at it this weekend; something I need as well for my main account.

**Comment by elliottcarlson** [comment]
@3mph4515 So, the cleanest way to authenticate an app that has TFA enabled, is to create app specific password at https://security.google.com/settings/security/apppasswords - more on this at https://support.google.com/accounts/answer/185833. This is obviously only OK in a situation when the system storing the application-specific password is one you trust.

**Pull request merged**
